### ISSUE TITLE
No such module 'SnapKit' Error In Demo.

### ISSUE THREAD

**Issue by Premal-Khetani** [SvenTiigi/FlyoverKit#3]
Hello, 
I just download the code and trying to run but it's showing Error that 

**FlyoverKit-master/FlyoverKitExample/ViewController.swift:11:8: No such module 'SnapKit'**

![screen shot 2018-02-26 at 11 24 41 am](https://user-images.githubusercontent.com/13691970/36655277-b0a8fb96-1ae7-11e8-99cf-cb4cf3304d7a.png)

**Comment by SvenTiigi** [comment]
Hey @Premal-Khetani,

In order to run the example Application you have to first generate the Frameworks (SnapKit) via [Carthage](https://github.com/Carthage/Carthage)

```bash
$ carthage update --platform iOS
$ open FlyoverKit.xcodeproj
```

You can install Carthage with [Homebrew](http://brew.sh/) using the following command:

```bash
$ brew update
$ brew install carthage
```

**Comment by SvenTiigi** [comment]
Hey @Premal-Khetani,

did this fix your problem?

**Comment by Premal-Khetani** [comment]
@SvenTiigi yet not i updated the carthage. let me try by tomorrow so i can tell you about this.

**Comment by Chandni-Solanki123** [comment]
Hi, 

I install Carthage and followed the steps that @SvenTiigi has mentioned. Still I am getting the same error :( 
"No such module 'SnapKit'"

**Comment by SvenTiigi** [comment]
Hey @Premal-Khetani,

is your problem still present?

**Comment by Premal-Khetani** [comment]
@SvenTiigi  yes its solved by updating Carthage. Thank you :)
