### ISSUE TITLE
Pod installation issue..

### ISSUE THREAD

**Issue by prakashmaharjan** [SvenTiigi/FlyoverKit#4]
When tried yo install with pod  

 it says...

[!] Unable to find a specification for `FlyoverKit`

in pod file : pod 'FlyoverKit'
...

**Comment by SvenTiigi** [comment]
Hey @PrakashMaharjan,

it seems like your local pod spec repo is outdated.

Please run:

```bash
pod repo update
```

Then run `pod install` on your `Podfile` and everything should be fine 🙌

**Comment by SvenTiigi** [comment]
Hey @PrakashMaharjan,

did this fix your problem?

**Comment by prakashmaharjan** [comment]
I guess its deployment target...What is the lowest deployment target to install FlyoverKit? I have target as iOS 9.0

It says as below... after pod update..
Specs satisfying the `FlyoverKit (~> 1.0.0)` dependency were found, but they required a higher minimum deployment target.

Thanks for reply.

**Comment by SvenTiigi** [comment]
The minimum deployment target for `FlyoverKit` is iOS 10.0 as it heavily depends on `UIViewPropertyAnimator` which is available >= iOS 10.0

**Comment by prakashmaharjan** [comment]
Yes @SvenTiigi, the deployment target was the issue.. I checked with target as iOS 10 minimum and there is no issue.

Thank you.
