### ISSUE TITLE
Iterate() through FlyoverAwesomePlace

### ISSUE THREAD

**Issue by elizabethsiegle** [SvenTiigi/FlyoverKit#6]
Trying to iterate over enum FlyoverAwesomePlace, keep getting error `Type 'FlyoverAwesomePlace' has no member 'iterate'`

**Comment by SvenTiigi** [comment]
Hey @elizabethsiegle 

In general the `FlyoverAwesomePlace.iterate()` function should be available.

I adopted `FlyoverAwesomePlace` to the new `CaseIterable` protocol and added a new release of `FlyoverKit` Version [`1.2.2`](https://github.com/SvenTiigi/FlyoverKit/releases/tag/1.2.2)

```swift
for place in FlyoverAwesomePlace.allCases {
    print(place)
}

for place in FlyoverAwesomePlace.iterate() {
    print(place)
}
```

Please update to the latest release and test it again 🙌

**Comment by elizabethsiegle** [comment]
That results in a lot of compiler issues!
![image](https://user-images.githubusercontent.com/8932430/46273549-d34a3200-c50a-11e8-8d2c-6e64ed9a09d1.png)

**Comment by SvenTiigi** [comment]
Seems like you are compiling FlyoverKit with < Swift 4.2

FlyoverKit has been updated with Version [1.2.1](https://github.com/SvenTiigi/FlyoverKit/releases/tag/1.2.1) to Swift 4.2

This is why for example [CaseIterable](https://developer.apple.com/documentation/swift/caseiterable) isn't recognized by the compiler
