### ISSUE TITLE
How to stop/pause the flyover

### ISSUE THREAD

**Issue by magnas35** [SvenTiigi/FlyoverKit#7]
Hi
I've integrated your FlyoverKit into a SwiftUI app with UIViewControllerRepresentable and it looks beautiful. I can manipulate the configuration properties just fine but for the life of me I can't work out how to pause the flyover. I have a `startStop` Bool binding and have tried this:
`uiViewController.flyoverMapView.flyoverCamera.state = startStop ? .started : .stopped`
to no avail. Any pointers would be much appreciated.

**Comment by SvenTiigi** [comment]
Hey @magnas35,

You can call the `stop()` function on a `FlyoverCamera` or `FlyoverMapView`

https://sventiigi.github.io/FlyoverKit/Classes/FlyoverCamera.html#/s:10FlyoverKit0A6CameraC4stopyyF
https://sventiigi.github.io/FlyoverKit/Classes/FlyoverMapView.html#/s:10FlyoverKit0A7MapViewC4stopyyF

Manipulating the `state` property from outside will have no effect. I will refactor the `state` property to:

```swift
public private(set) state: State
```

To make it more clear that the `state` can not be manipulated from the outside.

**Comment by magnas35** [comment]
Perfect and many thanks for the quick reply.
